// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ4WtvHk7fWhvGCAAn4Xlz-Awv0FAx2aM',
    appId: '1:99480301343:web:5685c6c98b567a49f1ca2a',
    messagingSenderId: '99480301343',
    projectId: 'brocode-2802a',
    authDomain: 'brocode-2802a.firebaseapp.com',
    storageBucket: 'brocode-2802a.appspot.com',
    measurementId: 'G-SW4XM6HMZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtdOZuvP9tHbWMWfbXjJvZQPTVfWyP--w',
    appId: '1:99480301343:android:954d185b9114b896f1ca2a',
    messagingSenderId: '99480301343',
    projectId: 'brocode-2802a',
    storageBucket: 'brocode-2802a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI7OzJN2zouI3SJBVmJCj3AqtE8sDVdbc',
    appId: '1:99480301343:ios:7e332a09568d4d02f1ca2a',
    messagingSenderId: '99480301343',
    projectId: 'brocode-2802a',
    storageBucket: 'brocode-2802a.appspot.com',
    iosClientId: '99480301343-0osmsferdlcrdnak0q8vmgl46m61rrci.apps.googleusercontent.com',
    iosBundleId: 'com.example.broCode02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI7OzJN2zouI3SJBVmJCj3AqtE8sDVdbc',
    appId: '1:99480301343:ios:7e332a09568d4d02f1ca2a',
    messagingSenderId: '99480301343',
    projectId: 'brocode-2802a',
    storageBucket: 'brocode-2802a.appspot.com',
    iosClientId: '99480301343-0osmsferdlcrdnak0q8vmgl46m61rrci.apps.googleusercontent.com',
    iosBundleId: 'com.example.broCode02',
  );
}
